version: '2'
services:
  hotelcovid19-app:
    image: hotelcovid19
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hotelcovid19-postgresql:5432/hotelcovid19
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  hotelcovid19-postgresql:
    extends:
      file: postgresql.yml
      service: hotelcovid19-postgresql
