version: '2'
services:
  hotelcovid19-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/hotelcovid19/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hotelcovid19
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
